Possibly Fix Travis CI

diff --git a/digits-test b/digits-test
--- a/digits-test
+++ b/digits-test
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 # Copyright (c) 2014-2017, NVIDIA CORPORATION.  All rights reserved.
 # Copyright (C) 2019, Nicholas Hubbard and contributors.
 
@@ -11,15 +11,15 @@ function set_exe {
     # $2 -- the executable
 
     # Check to make sure the executable exists
-    hash $2 2>/dev/null || { echo >&2 "ERROR: \"$2\" executable not found!"; exit 1; }
+    hash "$2" 2>/dev/null || { echo >&2 "ERROR: \"$2\" executable not found!"; exit 1; }
     # Print the path to the executable
     local __resultvar=$1
-    eval $__resultvar="'$(command -v $2)'"
+    eval "$__resultvar='$(command -v "$2")'"
 }
 
 # Some hacking necessary to respect virtualenv installations
 set_exe PYTHON_EXE python2
 set_exe NOSE_EXE nosetests
 
-DIGITS_MODE_TEST=1 $PYTHON_EXE $NOSE_EXE \
-    --no-path-adjustment $@
+DIGITS_MODE_TEST=1 $PYTHON_EXE "$NOSE_EXE" \
+    --no-path-adjustment "$@"
